name: Maven Central publishing

on:
  workflow_dispatch:

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Importing GPG key"
        run: |
          sudo echo ${{ secrets.GPG_PASSPHRASE }} | gpg --batch --yes --passphrase-fd 0 secring.gpg

      - name: "Publishing"
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew publish closeAndReleaseRepository -Dorg.gradle.project.signing.password=${{ secrets.GPG_PASSPHRASE }}